config/routes.rb
Rails.application.routes.draw do

root 'welcome#home'
get 'about', to: 'welcome#about'

resources :products
resources :orders
resources :users
resources :clients

get 'user/login', to: 'sessions#new'
post 'user/login', to: 'sessions#create'
delete 'user/logout', to: 'sessions#destroy'

get 'client/login', to: 'client_sessions#new'
post 'client/login', to: 'client_sessions#create'
delete 'client/logout', to: 'client_sessions#destroy'

get 'user/base', to: 'bases#index'
get 'client/base', to: 'client_bases#index'

end

app/controllers/client_sessions_controller.rb
class ClientSessionsController < ApplicationController
   
   def new
   
   end
   
   def create
        client = Client.find_by(u_name: params[:session][:u_name].downcase)
        
        if client && client.authenticate(params[:session][:password]) 
            session[:client_id] = client.id
            flash[:success] = "You are now logged in"
            redirect_to client_base_path(client)
        else
            flash.now[:danger] = "Incorrect User or Password"
            render 'new'
        end
   end
   
   def destroy
       session[:client_id] = nil
       flash[:success] = "You have logged out"
       redirect_to root_path
   end
    
end

app/views/client_sessions/new.html.erb
<h1>Client Log In</h1>

<%= form_for :session, url: client_login_path do |f| %>
    <p>
        <%= f.label :u_name, "Username" %>
        <%= f.text_field :u_name %>
    </p>
    <p>
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, autocomplete: "off" %>
    </p>
    <p>
        <%= f.submit "Log In"%>
    </p>
    
<% end %> 