config/routes.rb
Rails.application.routes.draw do

root 'welcome#home'
get 'about', to: 'welcome#about'

resources :products
resources :orders
resources :users
resources :clients

get 'user/login', to: 'sessions#new'
post 'user/login', to: 'sessions#create'
delete 'user/logout', to: 'sessions#destroy'

get 'client/login', to: 'client_sessions#new'
post 'client/login', to: 'client_sessions#create'
delete 'client/logout', to: 'client_sessions#destroy'

get 'user/base', to: 'bases#index'
get 'client/base', to: 'client_bases#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
    has_many :orders
    
     before_save { self.u_name = u_name.downcase }
    
    validates   :names, presence: true, length: { minimum: 3, maximum: 100 }
    
    validates   :ln1, presence: true, length: { minimum: 3, maximum: 50 }
    
                VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates   :email, presence: true, uniqueness: { case_sensitive: false }, 
                length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }
                
    validates   :u_name, presence: true, uniqueness: { case_sensitive: false }, 
                length: { minimum: 3, maximum: 25 }
                
    has_secure_password
    
    validates   :b_date, presence: true
    
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :set_client, only: [:edit, :update, :show, :destroy]
    before_action :require_client, except: [:new, :create]
    before_action :require_same_client, only: [:edit, :destroy]
   
    def index
       @clients = Client.all 
    end
    
    def new
        @client = Client.new
    end
    
    def show
    end
    
    def edit
    end
    
    def create
        # render plain: params[:client].inspect
        @client = Client.new(client_params)
        if @client.save
            session[:client_id] = @client.id
            flash[:notice] = "Account has been created"
            redirect_to client_base_path(@client)
        else
            render 'new' 
        end
        
    end
    
    def update
       if @client.update(client_params)
           flash[:notice] = "Account has been updated"
           redirect_to client_path(@client)
       else
           render 'edit'
       end
    end
    
    def destroy
       @client.destroy
       flash[:notice] = "Account has been deleted"
       redirect_to clients_path
    end
    
    private
    
    def client_params
       params.require(:client).permit(:names, :ln1, :ln2, :email, :u_name, :password, :b_date )
    end
    
    def set_client
       @client = Client.find(params[:id]) 
    end
    
    def require_same_client
        if current_client != @client && !current_user.admin?
            flash[:danger] = "That's not your info!"
            redirect_to root_path
        end
    end
    
end

app/views/clients/edit.html.erb
<h1>Update Your Info</h1>

<% if @client.errors.any? %>
<h2>Failed to create new user</h2>
    <ul>
        <% @client.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @client do |f| %>

    <p>
        <%= f.label :names, "Name" %>
        <%= f.text_field :names %>
    </p>
    <p>
        <%= f.label :ln1, "Lastname" %>
        <%= f.text_field :ln1 %>
    </p>
    <p>
        <%= f.label :ln2, "Lastname" %>
        <%= f.text_field :ln2 %>
    </p>
    <p>
        <%= f.label :email, "Email" %>
        <%= f.email_field :email %>
    </p>
    <p>
        <%= f.label :u_name, "Username" %>
        <%= f.text_field :u_name %>
    </p>
    <p>
        <%= f.label :password_digest, "Password" %>
        <%= f.password_field :password_digest %>
    </p>
    <p>
        <%= f.label :b_date, "Birthdate" %>
        <%= f.date_field :b_date %>
    </p>
    <p>
        <%= f.submit "Update Account" %>
    </p>
    
<% end %>

<p>
    <%= link_to 'Back to client list', clients_path %>
</p>

app/views/clients/index.html.erb
<h1>Registered Clients</h1>

<table>
        <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Registered</th>
        </tr>
        
    <% @clients.each do |u| %>
        <tr>
            <td><%= u.names %> <%= u.ln1 %> <%= u.ln2 %></td>
            <td><%= u.u_name %></td>
            <td><%= u.email %></td>
            <td><%= time_ago_in_words(u.created_at) %> ago</td>
            <td><%= link_to 'Edit', edit_client_path(u) %></td>
            <td><%= link_to 'Show', client_path(u) %></td>
            <td><%= link_to 'Delete', client_path(u), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
    <% end %>
</table>

app/views/clients/new.html.erb
<h1>Create Your New Account!</h1>

<% if @client.errors.any? %>
<h2>Failed to create new user</h2>
    <ul>
        <% @client.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @client do |f| %>

    <p>
        <%= f.label :names, "Name" %>
        <%= f.text_field :names %>
    </p>
    <p>
        <%= f.label :ln1, "Lastname" %>
        <%= f.text_field :ln1 %>
    </p>
    <p>
        <%= f.label :ln2, "Lastname" %>
        <%= f.text_field :ln2 %>
    </p>
    <p>
        <%= f.label :email, "Email" %>
        <%= f.email_field :email %>
    </p>
    <p>
        <%= f.label :u_name, "Username" %>
        <%= f.text_field :u_name %>
    </p>
    <p>
        <%= f.label :password, "Password" %>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.label :b_date, "Birthdate" %>
        <%= f.date_field :b_date %>
    </p>
    <p>
        <%= f.submit "Sign Up" %>
    </p>
    
<% end %>

app/views/clients/show.html.erb
<h1>This Is Your Personal Info, <%= @client.u_name.capitalize %></h1>

<table>
    <tr>
        <td>
            Name
        </td>
        <td>
            <%= @client.names.capitalize %> <%= @client.ln1.capitalize %> <%= @client.ln2.capitalize %>
        </td>
    </tr>
    <tr>
        <td>
            Username
        </td>
        <td>
            <%= @client.u_name %>
        </td>
    </tr>
    <tr>
        <td>
            Email
        </td>
        <td>
            <%= @client.email %>
        </td>
    </tr>
    <tr>
        <td>
            Password
        </td>
        <td>
            ********
        </td>
        <td>
            Link to change pw
        </td>
    </tr>
    <tr>
        <td>
            Registration Date
        </td>
        <td>
            <%= @client.created_at %>
        </td>
    </tr>
</table>

<p>
    <%= link_to 'Back to client list', clients_path %> | <%= link_to 'Edit', edit_client_path %>
</p>